[project]
name = "party"
dynamic = ["version", "description", "readme", "requires-python", "license", "authors", "keywords", "classifiers", "scripts", "dependencies"]

[build-system]
requires = ["pbr>=5.7.0", "setuptools>=36.6.0", "wheel"]
build-backend = "pbr.build"
